spring:
  application:
    name: sampada
  security:
    oauth2:
      client:
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
        registration:
          google:
            client-id: ${GOOGLE_AUTH_CLIENT_ID}
            client-secret: ${GOOGLE_AUTH_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile

app:
  ui:
    base: http://localhost:5173
    home: ${app.ui.base}/dashboard
  security:
    cors:
      allowed-origins:
        - http://localhost:5173
      allowed-headers:
        - Content-Type
        - Accept
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      exposed-headers:
        - Content-Type
        - Accept
        - Access-Control-Allow-Credentials
        - Access-Control-Allow-Origins
        - Access-Control-Allow-Headers
        - Access-Control-Allow-Credentials
      allowed-credentials: true
    state:
      issuer: ${spring.application.name}
      aud: google,github
      secret: AB27D88BC263D7033B0E9BB3331CB013C1A4F644EC6AA2CD40645F5AEACAB64E
      ttl: 300
      leeway: 30
    session:
      issuer: ${spring.application.name}
      secret: AB27D88BC263D7033B0E9BB3331CB013C1A4F644EC6AA2CD40645F5AEACAB64E
      ttl: 432000
      leeway: 30

instance_id: ${random.value}

logging:
  pattern:
    correlation: "[${instance_id:},%X{traceId:-},%X{spanId:-}]"
  include-application-name: true
